### ISSUE TITLE
[Unity]: It doesn't work... (atleast for me)

### ISSUE THREAD

**Issue by pavman69** [joshuah345/Discord-Stuff#6]
it wont work

step 1. enable the theme
step 2. wait for it to load
step 3. wait for it to load
step 4. get confused because it said it loaded ages ago but dont see anything happen
step 5. go to the messages and servers tab, nothing changed

i thought it would work

![image](https://github.com/joshuah345/Discord-Stuff/assets/139662164/4dbcad56-babb-430f-a21a-f3e264888799)
![image](https://github.com/joshuah345/Discord-Stuff/assets/139662164/f930895d-03ca-47bc-9e9f-957b1b037235)

 help

**Comment by LuSaffi** [comment]
hey @pavman69 ! I've requested a pull request for this very issue, just gotta wait for them to acknowledge the fix!

**Comment by pavman69** [comment]
> hey @pavman69 ! I've requested a pull request for this very issue, just gotta wait for them to acknowledge the fix!

okay thank you

**Comment by pavman69** [comment]
> hey @pavman69 ! I've requested a pull request for this very issue, just gotta wait for them to acknowledge the fix!

i changed the bit in the file which didnt work with your fixed version and it didnt work, is it because im using betterdiscord?

**Comment by pavman69** [comment]
> hey @pavman69 ! I've requested a pull request for this very issue, just gotta wait for them to acknowledge the fix!

switched to vencord, fixed

**Comment by joshuah345** [comment]
i had setup github pages with a custom domain and the redirect was breaking it
it no longer redirects and the new domain is there now
from now on you can link to my github repos using
https://tanuki.page/gh/Discord-Stuff for example
and the direct link to the theme.css is https://tanuki.page/Discord-Stuff/Themes/Unity/Unity.theme.css

(fixed in commit e0c02dcdf28bb460a25864430bd42d2229a3aaf9)
